# Generated by Django 3.1.4 on 2021-02-07 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20201229_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 17, 59, 26, 316999)),
        ),
    ]
